language: node_js

node_js:
  - "8"

services:
  - mongodb
  #- docker

install:
  - npm install

build:
  - scripts/release.sh $TRAVIS_BRANCH
  #docker build .

test:
  - npm test

# Push back to master with updated package.json and CHANGELOG
after_success:
  - scripts/push.sh $GH_TOKEN $TRAVIS_BRANCH

deploy:
  - provider: script
    script: scripts/deploy.sh
    on:
      branch: master