language: node_js

node_js:
  - "8"

services:
  - mongodb
  #- docker

install:
  - npm install

build:
  - script:
    - build-scripts/release.sh $TRAVIS_BRANCH
  #docker build .

test:
  - npm test

deploy:
  script:
    - build-scripts/deploy.sh

# Push back to master with updated package.json
after_success:
  script:
    - build-scripts/push.sh